const keysArray = [
  [
    {
      eng: '`',
      engShift: '~',
      rus: 'ё',
      rusShift: 'Ё',
      func: false,
      size: 'fix',
      id: 'Backquote',
      color: 'red',
    },
    {
      eng: '1',
      engShift: '!',
      rus: '1',
      rusShift: '!',
      func: false,
      size: 'fix',
      id: 'Digit1',
      color: 'red',
    },
    {
      eng: '2',
      engShift: '@',
      rus: '2',
      rusShift: '"',
      func: false,
      size: 'fix',
      id: 'Digit2',
      color: 'red',
    },
    {
      eng: '3',
      engShift: '#',
      rus: '3',
      rusShift: '№',
      func: false,
      size: 'fix',
      id: 'Digit3',
      color: 'red',
    },
    {
      eng: '4',
      engShift: '$',
      rus: '4',
      rusShift: ';',
      func: false,
      size: 'fix',
      id: 'Digit4',
      color: 'red',
    },
    {
      eng: '5',
      engShift: '%',
      rus: '5',
      rusShift: '%',
      func: false,
      size: 'fix',
      id: 'Digit5',
      color: 'red',
    },
    {
      eng: '6',
      engShift: '^',
      rus: '6',
      rusShift: ':',
      func: false,
      size: 'fix',
      id: 'Digit6',
      color: 'red',
    },
    {
      eng: '7',
      engShift: '&',
      rus: '7',
      rusShift: '?',
      func: false,
      size: 'fix',
      id: 'Digit7',
      color: 'red',
    },
    {
      eng: '8',
      engShift: '*',
      rus: '8',
      rusShift: '*',
      func: false,
      size: 'fix',
      id: 'Digit8',
      color: 'red',
    },
    {
      eng: '9',
      engShift: '(',
      rus: '9',
      rusShift: '(',
      func: false,
      size: 'fix',
      id: 'Digit9',
      color: 'red',
    },
    {
      eng: '0',
      engShift: ')',
      rus: '0',
      rusShift: ')',
      func: false,
      size: 'fix',
      id: 'Digit0',
      color: 'red',
    },
    {
      eng: '-',
      engShift: '_',
      rus: '-',
      rusShift: '_',
      func: false,
      size: 'fix',
      id: 'Minus',
      color: 'red',
    },
    {
      eng: '=',
      engShift: '+',
      rus: '=',
      rusShift: '+',
      func: false,
      size: 'fix',
      id: 'Equal',
      color: 'red',
    },
    {
      eng: 'Backspace',
      engShift: 'Backspace',
      rus: 'Backspace',
      rusShift: 'Backspace',
      func: true,
      size: 'flex',
      id: 'Backspace',
      color: 'blue',
    },
  ],
  [
    {
      eng: 'Tab',
      engShift: 'Tab',
      rus: 'Tab',
      rusShift: 'Tab',
      func: true,
      size: 'flex',
      id: 'Tab',
      color: 'blue',
    },
    {
      eng: 'q',
      engShift: 'Q',
      rus: 'й',
      rusShift: 'Й',
      func: false,
      size: 'fix',
      id: 'KeyQ',
      color: 'red',
    },
    {
      eng: 'w',
      engShift: 'W',
      rus: 'ц',
      rusShift: 'Ц',
      func: false,
      size: 'fix',
      id: 'KeyW',
      color: 'red',
    },
    {
      eng: 'e',
      engShift: 'E',
      rus: 'у',
      rusShift: 'У',
      func: false,
      size: 'fix',
      id: 'KeyE',
      color: 'red',
    },
    {
      eng: 'r',
      engShift: 'R',
      rus: 'к',
      rusShift: 'К',
      func: false,
      size: 'fix',
      id: 'KeyR',
      color: 'red',
    },
    {
      eng: 't',
      engShift: 'T',
      rus: 'е',
      rusShift: 'Е',
      func: false,
      size: 'fix',
      id: 'KeyT',
      color: 'red',
    },
    {
      eng: 'y',
      engShift: 'Y',
      rus: 'н',
      rusShift: 'Н',
      func: false,
      size: 'fix',
      id: 'KeyY',
      color: 'red',
    },
    {
      eng: 'u',
      engShift: 'U',
      rus: 'г',
      rusShift: 'Г',
      func: false,
      size: 'fix',
      id: 'KeyU',
      color: 'red',
    },
    {
      eng: 'i',
      engShift: 'I',
      rus: 'ш',
      rusShift: 'Ш',
      func: false,
      size: 'fix',
      id: 'KeyI',
      color: 'red',
    },
    {
      eng: 'o',
      engShift: 'O',
      rus: 'щ',
      rusShift: 'Щ',
      func: false,
      size: 'fix',
      id: 'KeyO',
      color: 'red',
    },
    {
      eng: 'p',
      engShift: 'P',
      rus: 'з',
      rusShift: 'З',
      func: false,
      size: 'fix',
      id: 'KeyP',
      color: 'red',
    },
    {
      eng: '[',
      engShift: '{',
      rus: 'х',
      rusShift: 'Х',
      func: false,
      size: 'fix',
      id: 'BracketLeft',
      color: 'red',
    },
    {
      eng: ']',
      engShift: '}',
      rus: 'ъ',
      rusShift: 'Ъ',
      func: false,
      size: 'fix',
      id: 'BracketRight',
      color: 'red',
    },
    {
      eng: '\\',
      engShift: '|',
      rus: '\\',
      rusShift: '/',
      func: false,
      size: 'fix',
      id: 'Backslash',
      color: 'red',
    },
    {
      eng: 'Del',
      engShift: 'Del',
      rus: 'Del',
      rusShift: 'Del',
      func: true,
      size: 'fix',
      id: 'Delete',
      color: 'blue',
    },
  ],
  [
    {
      eng: 'CapsLock',
      engShift: 'CapsLock',
      rus: 'CapsLock',
      rusShift: 'CapsLock',
      func: true,
      size: 'flex',
      id: 'CapsLock',
      color: 'blue',
    },
    {
      eng: 'a',
      engShift: 'A',
      rus: 'ф',
      rusShift: 'Ф',
      func: false,
      size: 'fix',
      id: 'KeyA',
      color: 'red',
    },
    {
      eng: 's',
      engShift: 'S',
      rus: 'ы',
      rusShift: 'Ы',
      func: false,
      size: 'fix',
      id: 'KeyS',
      color: 'red',
    },
    {
      eng: 'd',
      engShift: 'D',
      rus: 'в',
      rusShift: 'В',
      func: false,
      size: 'fix',
      id: 'KeyD',
      color: 'red',
    },
    {
      eng: 'f',
      engShift: 'F',
      rus: 'а',
      rusShift: 'А',
      func: false,
      size: 'fix',
      id: 'KeyF',
      color: 'red',
    },
    {
      eng: 'g',
      engShift: 'G',
      rus: 'п',
      rusShift: 'П',
      func: false,
      size: 'fix',
      id: 'KeyG',
      color: 'red',
    },
    {
      eng: 'h',
      engShift: 'H',
      rus: 'р',
      rusShift: 'Р',
      func: false,
      size: 'fix',
      id: 'KeyH',
      color: 'red',
    },
    {
      eng: 'j',
      engShift: 'J',
      rus: 'о',
      rusShift: 'О',
      func: false,
      size: 'fix',
      id: 'KeyJ',
      color: 'red',
    },
    {
      eng: 'k',
      engShift: 'K',
      rus: 'л',
      rusShift: 'Л',
      func: false,
      size: 'fix',
      id: 'KeyK',
      color: 'red',
    },
    {
      eng: 'l',
      engShift: 'L',
      rus: 'д',
      rusShift: 'Д',
      func: false,
      size: 'fix',
      id: 'KeyL',
      color: 'red',
    },
    {
      eng: ';',
      engShift: ':',
      rus: 'ж',
      rusShift: 'Ж',
      func: false,
      size: 'fix',
      id: 'Semicolon',
      color: 'red',
    },
    {
      eng: "'",
      engShift: '"',
      rus: 'э',
      rusShift: 'Э',
      func: false,
      size: 'fix',
      id: 'Quote',
      color: 'red',
    },
    {
      eng: 'Enter',
      engShift: 'Enter',
      rus: 'Enter',
      rusShift: 'Enter',
      func: true,
      size: 'flex',
      id: 'Enter',
      color: 'blue',
    },
  ],
  [
    {
      eng: 'Shift',
      engShift: 'Shift',
      rus: 'Shift',
      rusShift: 'Shift',
      func: true,
      size: 'flex',
      id: 'ShiftLeft',
      color: 'blue',
    },
    {
      eng: 'z',
      engShift: 'Z',
      rus: 'я',
      rusShift: 'Я',
      func: false,
      size: 'fix',
      id: 'KeyZ',
      color: 'red',
    },
    {
      eng: 'x',
      engShift: 'X',
      rus: 'ч',
      rusShift: 'Ч',
      func: false,
      size: 'fix',
      id: 'KeyX',
      color: 'red',
    },
    {
      eng: 'c',
      engShift: 'C',
      rus: 'с',
      rusShift: 'С',
      func: false,
      size: 'fix',
      id: 'KeyC',
      color: 'red',
    },
    {
      eng: 'v',
      engShift: 'V',
      rus: 'м',
      rusShift: 'М',
      func: false,
      size: 'fix',
      id: 'KeyV',
      color: 'red',
    },
    {
      eng: 'b',
      engShift: 'B',
      rus: 'и',
      rusShift: 'И',
      func: false,
      size: 'fix',
      id: 'KeyB',
      color: 'red',
    },
    {
      eng: 'n',
      engShift: 'N',
      rus: 'т',
      rusShift: 'Т',
      func: false,
      size: 'fix',
      id: 'KeyN',
      color: 'red',
    },
    {
      eng: 'm',
      engShift: 'M',
      rus: 'ь',
      rusShift: 'Ь',
      func: false,
      size: 'fix',
      id: 'KeyM',
      color: 'red',
    },
    {
      eng: ',',
      engShift: '<',
      rus: 'б',
      rusShift: 'Б',
      func: false,
      size: 'fix',
      id: 'Comma',
      color: 'red',
    },
    {
      eng: '.',
      engShift: '>',
      rus: 'ю',
      rusShift: 'Ю',
      func: false,
      size: 'fix',
      id: 'Period',
      color: 'red',
    },
    {
      eng: '/',
      engShift: '?',
      rus: '.',
      rusShift: ',',
      func: false,
      size: 'fix',
      id: 'Slash',
      color: 'red',
    },
    {
      eng: '△',
      engShift: '△',
      rus: '△',
      rusShift: '△',
      func: false,
      size: 'fix',
      id: 'ArrowUp',
      color: 'blue',
    },
    {
      eng: 'Shift',
      engShift: 'Shift',
      rus: 'Shift',
      rusShift: 'Shift',
      func: true,
      size: 'flex',
      id: 'ShiftRight',
      color: 'blue',
    },
  ],
  [
    {
      eng: 'Ctrl',
      engShift: 'Ctrl',
      rus: 'Ctrl',
      rusShift: 'Ctrl',
      func: true,
      size: 'fix',
      id: 'ControlLeft',
      color: 'blue',
    },
    {
      eng: 'Win',
      engShift: 'Win',
      rus: 'Win',
      rusShift: 'Win',
      func: true,
      size: 'fix',
      id: 'MetaLeft',
      color: 'blue',
    },
    {
      eng: 'Alt',
      engShift: 'Alt',
      rus: 'Alt',
      rusShift: 'Alt',
      func: true,
      size: 'fix',
      id: 'AltLeft',
      color: 'blue',
    },
    {
      eng: ' ',
      engShift: ' ',
      rus: ' ',
      rusShift: ' ',
      func: true,
      size: 'flex',
      id: 'Space',
      color: 'red',
    },
    {
      eng: 'Alt',
      engShift: 'Alt',
      rus: 'Alt',
      rusShift: 'Alt',
      func: true,
      size: 'fix',
      id: 'AltRight',
      color: 'blue',
    },
    {
      eng: '◁',
      engShift: '◁',
      rus: '◁',
      rusShift: '◁',
      func: false,
      size: 'fix',
      id: 'ArrowLeft',
      color: 'blue',
    },
    {
      eng: '▽',
      engShift: '▽',
      rus: '▽',
      rusShift: '▽',
      func: false,
      size: 'fix',
      id: 'ArrowDown',
      color: 'blue',
    },
    {
      eng: '▷',
      engShift: '▷',
      rus: '▷',
      rusShift: '▷',
      func: false,
      size: 'fix',
      id: 'ArrowRight',
      color: 'blue',
    },
    {
      eng: 'Ctrl',
      engShift: 'Ctrl',
      rus: 'Ctrl',
      rusShift: 'Ctrl',
      func: true,
      size: 'fix',
      id: 'ControlRight',
      color: 'blue',
    },
  ],
];

export default keysArray;
